### ISSUE TITLE
Popup problems with Colibris skin

### ISSUE THREAD

**Issue by brettcs** [ether/ep_email_notifications#40]
With the Colibris skin, the popup looks like this:

![Screenshot from 2020-10-30 09-29-15](https://user-images.githubusercontent.com/4948878/97718764-b04d2c00-1a9c-11eb-9fd6-b04853e771f8.png)

Problems with this:

* The × in the title doesn't do anything, the real close button is on the right. It should be removed.
* The "on" slider for "starts editing the pad" isn't visible. It is apparently still there in the DOM somewhere; the mouse cursor changes when you hover over where it should be.
* Neither slider seems to be toggle-able. Clicking on them doesn't do anything.
* This is less important but center-justifying the options below the email address box seems like less than ideal presentation. Better to have all that left-justified if possible.

**Comment by JohnMcLear** [comment]
Actually this is completely changed since about last week..  Pop up no longer includes HTML, user must visit settings to subsribe.

**Comment by JohnMcLear** [comment]
Update Etherpad and the plugin :)

**Comment by brettcs** [comment]
I just upgraded Etherpad last night to 1.8.6, and I tried to upgrade the plugin too (although my admin interface says I only have 0.1.15 vs. 0.1.17 in Git). Can you please let me know what versions of each I need to be running?

**Comment by JohnMcLear** [comment]
Try clear browser cache.  Also set minify to false and maxage to 0 if this is a dev instance
